### ISSUE TITLE
An idea to split the rules into logical parts

### ISSUE THREAD

**Issue by DopustimVladimir** [coffeelint/coffeelint#178]
I have an idea to split the rules into logical parts. For example...

Possible errors:

- cyclomatic_complexity
- duplicate_key
- indentation
- line_endings
- missing_fat_arrows
- missing_parseint_radix
- no_backticks
- no_debugger
- no_empty_functions
- no_interpolation_in_single_quotes
- no_nested_string_interpolation
- no_throwing_strings

Stylistic issues:

... all other rules

We can just add the "type" property for each rule. For example...

```
rule:
    type: 'possible_error'
    name: 'cyclomatic_complexity'
    level: 'ignore'
    message: 'The cyclomatic complexity is too damn high'
    value: 10
    description: '''
        Examine the complexity of your function.
        '''
```

How do you think about this?
